# Generated by Django 3.0.6 on 2020-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_auto_20200729_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extras',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='publications',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(choices=[('ST', 'Inżynier'), ('lic.', 'Licencjat'), ('mgr', 'Magister'), ('mgr inż.', 'Magister inżyner'), ('dr', 'Doktor'), ('dr hab.', 'Doktor habilitowany'), ('prof.', 'Profesor')], default='ST', max_length=8),
        ),
        migrations.DeleteModel(
            name='ProfProfile',
        ),
    ]
