# Generated by Django 3.0.6 on 2020-07-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_userfiles_userfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfolder',
            name='parent',
        ),
    ]
