# Generated by Django 3.0.6 on 2020-07-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0005_remove_userfolder_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFiles',
        ),
        migrations.DeleteModel(
            name='UserFolder',
        ),
    ]
