# Generated by Django 3.0.6 on 2020-07-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0010_auto_20200730_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfiles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userfiles',
            name='user',
        ),
    ]
