# Generated by Django 3.0.6 on 2020-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0011_auto_20200730_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(choices=[('inz', 'Inżynier'), ('lic.', 'Licencjat'), ('mgr', 'Magister'), ('mgr inz.', 'Magister inżyner'), ('dr', 'Doktor'), ('dr hab.', 'Doktor habilitowany'), ('prof.', 'Profesor')], default='inz', max_length=8),
        ),
    ]
