# Generated by Django 3.0.6 on 2020-09-23 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_manage', '0012_auto_20200803_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='publications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='USOSlink',
            field=models.URLField(default='-'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(choices=[('inz.', 'Inżynier'), ('lic.', 'Licencjat'), ('mgr', 'Magister'), ('mgr inz.', 'Magister inżyner'), ('dr', 'Doktor'), ('dr hab.', 'Doktor habilitowany'), ('prof.', 'Profesor')], default='inz.', max_length=8),
        ),
        migrations.CreateModel(
            name='UserPublications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('extras', models.TextField()),
                ('education', models.TextField()),
                ('hobbies', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
