# Generated by Django 3.0.6 on 2020-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0015_auto_20200928_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(default=1, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
